import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from 'next/link';
import { FaTwitter, FaFacebook, FaInstagram, FaYoutube } from "react-icons/fa";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <header className="w-full bg-blue-700 py-4 flex items-center justify-between px-8 shadow-md">
      <h1 className="text-4xl text-white font-bold ">ResuMate</h1>
      <h3 className="font-semibold italic  mr-48 mt-3 tracking-wide bg-gradient-to-r from-blue-200 to-purple-400 bg-clip-text text-transparent">Build, Edit, Succeed!</h3>

        <nav className="flex space-x-4 font-semibold">
        <Link href="http://localhost:3000/">
            <button className="px-4 py-1.5 bg-gray-100 text-blue-600 rounded-md hover:bg-gray-300">
              Home
            </button>
          </Link>
          <Link href="/fill-details">
            <button className="px-4 py-1.5 bg-gray-100 text-blue-600 rounded-md hover:bg-gray-300">
              Build Resume
            </button>
          </Link>
          <Link href="/templates">
            <button className="px-4 py-1.5 bg-gray-100 text-blue-600 rounded-md hover:bg-gray-300">
              Templates
            </button>
          </Link>
          <Link href="/about">
            <button className="px-4 py-1.5 bg-gray-100 text-blue-600 rounded-md hover:bg-gray-300">
              About Us
            </button>
          </Link>
          <div className="relative">
            <input
              type="text"
              placeholder="Search..."
              className="font-light px-4 py-1.5 rounded-md text-gray-900 focus:outline-none focus:ring-2 focus:ring-blue-300"
            />
            <button
              type="submit"
              className="absolute right-1 top-1 bg-blue-600 text-white px-2 py-0.5 rounded-md hover:bg-blue-700 font-normal"
            >
              Search
            </button>
          </div>
        </nav>
      </header>

        {children}
        <footer className="bg-black text-white p-4">
      <div className="container mx-auto flex justify-between items-center">

        {/* Left side: Copyright text */}
        <div className="text-left text-gray-300">
          <p>© 2024 Your Company, Inc. All rights reserved.</p>
          <div className="mt-1 space-x-4 text-gray-400 text-sm">
            <Link href="/privacy-policy" className="hover:text-white hover:underline">Privacy Policy</Link>
            <Link href="/terms-of-service" className="hover:text-white hover:underline">Terms of Service</Link>
            <Link href="/contact" className="hover:text-white hover:underline">Contact Us</Link>
          </div>
        </div>

        {/* Right side: Social Media Icons and "Made by" link */}
        <div className="flex flex-col items-end">
          {/* Social Media Icons */}
          <div className="flex space-x-4 mb-1">
            <Link href="https://twitter.com" aria-label="Twitter">
              <FaTwitter className="text-white hover:text-blue-500 hover:underline" size={24} />
            </Link>
            <Link href="https://facebook.com" aria-label="Facebook">
              <FaFacebook className="text-white hover:text-blue-700 " size={24} />
            </Link>
            <Link href="https://instagram.com" aria-label="Instagram">
              <FaInstagram className="text-white hover:text-pink-500 " size={24} />
            </Link>
            <Link href="https://youtube.com" aria-label="YouTube">
              <FaYoutube className="text-white hover:text-red-600 " size={24} />
            </Link>
          </div>
          {/* Made by Link */}
          <Link href="https://www.linkedin.com/in/hamza-iqbal123/" className="text-gray-400 hover:text-white">Muhammad Hamza Iqbal</Link>
        </div>

      </div>
    </footer>
      </body>
    </html>
  );
}
